[2025-08-26T10:04:49.214+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mamda_monthly_etl_pipeline.check_status_files manual__2025-08-26T10:04:45.703707+00:00 [queued]>
[2025-08-26T10:04:49.224+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mamda_monthly_etl_pipeline.check_status_files manual__2025-08-26T10:04:45.703707+00:00 [queued]>
[2025-08-26T10:04:49.225+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2025-08-26T10:04:49.238+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): check_status_files> on 2025-08-26 10:04:45.703707+00:00
[2025-08-26T10:04:49.244+0000] {standard_task_runner.py:60} INFO - Started process 147 to run task
[2025-08-26T10:04:49.247+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'mamda_monthly_etl_pipeline', 'check_status_files', 'manual__2025-08-26T10:04:45.703707+00:00', '--job-id', '199', '--raw', '--subdir', 'DAGS_FOLDER/mamda_monthly_etl.py', '--cfg-path', '/tmp/tmpsr77dszk']
[2025-08-26T10:04:49.249+0000] {standard_task_runner.py:88} INFO - Job 199: Subtask check_status_files
[2025-08-26T10:04:49.306+0000] {task_command.py:423} INFO - Running <TaskInstance: mamda_monthly_etl_pipeline.check_status_files manual__2025-08-26T10:04:45.703707+00:00 [running]> on host c7bb110c70ae
[2025-08-26T10:04:49.390+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='mamda_etl' AIRFLOW_CTX_DAG_ID='mamda_monthly_etl_pipeline' AIRFLOW_CTX_TASK_ID='check_status_files' AIRFLOW_CTX_EXECUTION_DATE='2025-08-26T10:04:45.703707+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-26T10:04:45.703707+00:00'
[2025-08-26T10:04:49.392+0000] {mamda_monthly_etl.py:122} INFO - === CHECK: STATUS FILES ===
[2025-08-26T10:04:49.393+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.11/site-packages/***/utils/context.py:315: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2025-08-26T10:04:49.395+0000] {mamda_monthly_etl.py:137} WARNING - Status directory not found: /opt/***/data/fee_payouts_status
[2025-08-26T10:04:49.410+0000] {python.py:202} INFO - Done. Returned value was: False
[2025-08-26T10:04:49.431+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=mamda_monthly_etl_pipeline, task_id=check_status_files, execution_date=20250826T100445, start_date=20250826T100449, end_date=20250826T100449
[2025-08-26T10:04:49.460+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-08-26T10:04:49.483+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
