[2025-08-26T14:39:56.792+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mamda_monthly_etl_pipeline.run_db_to_file_etl manual__2025-08-26T14:39:53.680390+00:00 [queued]>
[2025-08-26T14:39:56.804+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mamda_monthly_etl_pipeline.run_db_to_file_etl manual__2025-08-26T14:39:53.680390+00:00 [queued]>
[2025-08-26T14:39:56.805+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2025-08-26T14:39:56.818+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): run_db_to_file_etl> on 2025-08-26 14:39:53.680390+00:00
[2025-08-26T14:39:56.825+0000] {standard_task_runner.py:60} INFO - Started process 534 to run task
[2025-08-26T14:39:56.828+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'mamda_monthly_etl_pipeline', 'run_db_to_file_etl', 'manual__2025-08-26T14:39:53.680390+00:00', '--job-id', '372', '--raw', '--subdir', 'DAGS_FOLDER/mamda_monthly_etl.py', '--cfg-path', '/tmp/tmpf4yo5ppu']
[2025-08-26T14:39:56.829+0000] {standard_task_runner.py:88} INFO - Job 372: Subtask run_db_to_file_etl
[2025-08-26T14:39:56.880+0000] {task_command.py:423} INFO - Running <TaskInstance: mamda_monthly_etl_pipeline.run_db_to_file_etl manual__2025-08-26T14:39:53.680390+00:00 [running]> on host 40a873810464
[2025-08-26T14:39:56.963+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='mamda_etl' AIRFLOW_CTX_DAG_ID='mamda_monthly_etl_pipeline' AIRFLOW_CTX_TASK_ID='run_db_to_file_etl' AIRFLOW_CTX_EXECUTION_DATE='2025-08-26T14:39:53.680390+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-26T14:39:53.680390+00:00'
[2025-08-26T14:39:56.964+0000] {mamda_monthly_etl.py:92} INFO - === START: DB -> FILE ETL ===
[2025-08-26T14:39:56.965+0000] {mamda_monthly_etl.py:78} INFO - Subprocess ENV: DATA_DIR_FEE_PAYOUTS -> /mnt/mamda_data/fee_payouts
[2025-08-26T14:39:56.965+0000] {mamda_monthly_etl.py:79} INFO - Subprocess ENV: DATA_DIR_FEE_STATUS -> /mnt/mamda_data/fee_payouts_status
[2025-08-26T14:39:59.827+0000] {mamda_monthly_etl.py:106} INFO - DB->FILE STDOUT:
Utilisation du dossier externe
Utilisation du dossier externe
Utilisation du dossier externe
Utilisation du dossier externe

[2025-08-26T14:39:59.828+0000] {mamda_monthly_etl.py:108} WARNING - DB->FILE STDERR:
INFO:__main__:---- DÉMARRAGE DU PIPELINE DB -> FILE ----
INFO:__main__:--- Traitement pour base: sinauto_mcma_, type_aux: A ---
INFO:__main__:Données extraites avec succès pour sinauto_mcma_
INFO:__main__:sinauto_mcma_ : mapping réussi
INFO:__main__:sinauto_mcma_ : transformation réussie
ERROR:__main__:Erreur lors du traitement de sinauto_mcma_, type_aux=A : [Errno 13] Permission denied: '/mnt/mamda_data/fee_payouts/Avocats'
INFO:__main__:--- Traitement pour base: sinauto_mcma_, type_aux: E ---
INFO:__main__:Données extraites avec succès pour sinauto_mcma_
INFO:__main__:sinauto_mcma_ : mapping réussi
INFO:__main__:sinauto_mcma_ : transformation réussie
ERROR:__main__:Erreur lors du traitement de sinauto_mcma_, type_aux=E : [Errno 13] Permission denied: '/mnt/mamda_data/fee_payouts/Experts Automobiles'
INFO:__main__:--- Traitement pour base: sinauto_mcma_, type_aux: M ---
INFO:__main__:Données extraites avec succès pour sinauto_mcma_
INFO:__main__:sinauto_mcma_ : mapping réussi
INFO:__main__:sinauto_mcma_ : transformation réussie
ERROR:__main__:Erreur lors du traitement de sinauto_mcma_, type_aux=M : [Errno 13] Permission denied: '/mnt/mamda_data/fee_payouts/Medecins'
INFO:__main__:--- Traitement pour base: sinauto_mcma_, type_aux: C ---
INFO:__main__:Données extraites avec succès pour sinauto_mcma_
INFO:__main__:sinauto_mcma_ : mapping réussi
INFO:__main__:sinauto_mcma_ : transformation réussie
ERROR:__main__:Erreur lors du traitement de sinauto_mcma_, type_aux=C : [Errno 13] Permission denied: '/mnt/mamda_data/fee_payouts/Experts Comptables'
INFO:__main__:---- FIN DU PIPELINE DB -> FILE ----

[2025-08-26T14:39:59.828+0000] {mamda_monthly_etl.py:116} INFO - === DONE: DB -> FILE ETL ===
[2025-08-26T14:39:59.829+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-08-26T14:39:59.840+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=mamda_monthly_etl_pipeline, task_id=run_db_to_file_etl, execution_date=20250826T143953, start_date=20250826T143956, end_date=20250826T143959
[2025-08-26T14:39:59.895+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-08-26T14:39:59.917+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
